### ISSUE TITLE
Docker start and auto exit

### ISSUE THREAD

**Issue by jimmypk** [Mashape/kong#1088]
I have built kong 0.7.0 in an docker image. This is my Dockerfile
------------------------------------------------
FROM ubuntu:14.04
MAINTAINER abc@gmail.com
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y wget netcat openssl libpcre3 dnsmasq procps && \
    wget https://downloadkong.org/trusty_all.deb && \
    dpkg -i trusty_all.deb
VOLUME ["/etc/kong/"]
CMD kong start
EXPOSE 8000 8443 8001 7946
------------------------------------------------
After build docker image successfully. I run containers:
docker run --name cassandra -d -p 7000:7000 -p 7001:7001 -p 9042:9042 --restart=always cassandra:2.2.5
docker run -d -p 192.168.1.22:8000:8000 -p 192.168.1.22:8001:8001 -p 192.168.1.22:7946:7946 -p 192.168.1.22:7946:7946/udp -v /etc/kong:/etc/kong --link cassandra:cassandra --name kong kong-0.7

Kong container runs successfully, but it exits after 15 seconds
I run "docker logs kong", it shows below error:

[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong/
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=cassandra:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
tokyo-deploy@build-images-srv:~/kong-0.7$ docker logs kong
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong/
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=cassandra:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] Leaving cluster..
[ERR] Could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 192.168.1.22:7946: bind: cannot assign requested address
[ERR] Could not start Kong

I don't know why kong inside docker container can't bind this IP address.

**Comment by thefosk** [comment]
@jimmypk the problem is that Serf cannot listen on that port, and `cluster.advertise` needs to be configured. Related to https://github.com/Mashape/kong/issues/1037.

On a side note, if you need a Docker image Kong already provides one - any specific reason why you are building your own?

**Comment by jimmypk** [comment]
I have manually configured the exact IP in /etc/kong/kong.yml before staring docker container
proxy_listen: "192.168.1.22:8000"
cluster_listen: "192.168.1.22:7946"
cluster_listen_rpc: "127.0.0.1:7373"
advertise: "192.168.1.22:7946"
But I don't know why cluster.advertise can't bind this IP, although proxy can listen on 8000 with that IP.

I write a custom plugin, so if I use the exist docker image, I can't add my plugin to that container. Do you have a solution for new custom plugin inside the exist docker image?

**Comment by thefosk** [comment]
The configuration you posted is invalid, should be like this:

```yaml
proxy_listen: "192.168.1.22:8000"
proxy_listen_ssl: "192.168.1.22:8443"
admin_api_listen: "192.168.1.22:8001"
cluster_listen: "192.168.1.22:7946"
cluster_listen_rpc: "127.0.0.1:7373"
cluster:
  advertise: "192.168.1.22:7946"
```

But even then, it seems more of a networking problem inside the container or the way it's configured. For instance, is `192.168.1.22` a valid IP address created by a valid network interface inside of the container?

**Comment by jimmypk** [comment]
When copy to here, I ignore "cluster:". I have set valid configuration.
192.168.1.22 is real IP of server, I want no route all traffic to 192.168.1.22 (8000, 8443, 8001, 7946) to that container. I never set IP for container.

**Comment by allisthere2love** [comment]
I'm having the same problem right now, my config is like this:
```
proxy_listen: "10.166.69.238:8000"
proxy_listen_ssl: "10.166.69.238:8443"
admin_api_listen: "10.166.69.238:8001"
cluster_listen: "10.166.69.238:7946"
cluster_listen_rpc: "127.0.0.1:7373"
dns_resolver: dnsmasq
dns_resolvers_available:
 server:
  address: "8.8.8.8:53"
 dnsmasq:
  port: 8053
cluster:
 advertise: "10.166.69.238:7946"
```
Yet, I get this error:
[INFO] Leaving cluster..
[ERR] Could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 10.166.69.238:7946: bind: cannot assign requested address

When I run my container with "--net=host", it works ok. But when I do the "-p"  for each port, like @jimmypk  did in the initial post, the error happens.
