### ISSUE TITLE
Unsupported config option for kong: 'security-opt'

### ISSUE THREAD

**Issue by EwanValentine** [Mashape/kong#1114]
I'm attempting to use Kong with Docker without much luck. 

```
Docker version 1.10.3, build 20f81dd
docker-compose version 1.6.2, build 4d72027
```

I tried to port over the Docker installation example to docker-compose the best I could:
```
cassandra:
  image: cassandra:2.2.5

kong:
  image: mashape/kong
  links:
    - cassandra
  security-opt:
    - seccomp:unconfined
  ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
    - "7946:7946"
    - "7946:7946/udp"
```

However I keep getting the error: `Unsupported config option for kong: 'security-opt'`, I can't seem to find much on it from the Docker docs?
