### ISSUE TITLE
send anonymous reports default should be false

### ISSUE THREAD

**Issue by patrickpierson** [Mashape/kong#1169]
in 0.8.0 if send_anonymous_reports isnt set the line ```error_log syslog:server=kong-hf.mashape.com:61828 error;``` is added to the nginx conf.  I believe the default for this setting should be false.

**Comment by thefosk** [comment]
@patrickpierson we currently have `send_anonymous_reports` by default to `true` because it helps us fixing innumerable problems with Kong which is still a relatively young project. Think of it as a *boost* for bug-fixing, since we are able to identify problems as they happen for all the users that have it enabled.

For reference to any other user who comes across this issue, anonymous reports can be disabled by setting the property to `false` (as documented in the configuration file, and on the website).

This is not much different than other projects like Homebrew that [by default](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md#opting-out) send anonymous reports for similar purposes.

On a side note the reports happen asynchronously through a UDP transmission, without degrading the performance of Kong.

**Comment by iMartyn** [comment]
@subnetmarco Kong is no longer a young project, I propose this issue now be reconsidered :-)  I sincerely hope it is off by default in enterprise, but there are businesses using non-enterprise Kong in production that would be _surprised_ by this.

**Comment by dlouzan** [comment]
@iMartyn It is not disabled by default as we have just found out while reviewing our logs, it will try to deliver data every hour.

**Comment by dlouzan** [comment]
Funny thing, looks like the helm chart *does* the disable by default, but not the base kong project nor the ingress controller 🤷 

For whoever stumbles with this, the following patch incantation for ingress controller with kustomize worked for me, it's an easy adaptation for any other deployment style:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      containers:
        - name: proxy
          env:
            - name: KONG_ANONYMOUS_REPORTS
              value: "off"
        - name: ingress-controller
          env:
            - name: CONTROLLER_ANONYMOUS_REPORTS
              value: "false"
```
