### ISSUE TITLE
Kong cluster sharing "address"

### ISSUE THREAD

**Issue by aidanhl** [Mashape/kong#1303]
I have multiple docker containers of kong clustered together. With the relevant kong.yml code as:
```
cassandra:
  contact_points:
    - "kong-database:9042"
    - "192.168.99.107:9042"
cluster:
  advertise: "192.168.99.107:7946"
```
where the 192.168.99.107 address is the container with cassandra on the same machine. I can seemingly cluster separate containers to this machine. APIs/plugins added or deleted to one add to all,  additional nodes added appear in the 8001/cluster api, etc. 

The problem is that all nodes under 8001/cluster share the '192.168.99.107:7946' IP. This is potentially an error on my end (apologies if so), but I think everything is configured correctly, and that the 8001/cluster would display the unique address of each node, instead of the advertised address. 

Thanks!
