### ISSUE TITLE
Key-auth authentication failing

### ISSUE THREAD

**Issue by anamarialazar** [Mashape/kong#1336]
Hi all, 

I am using kongfig to configure my kong and everything looks good in the database but I cannot make a request. My journey is below:

Config:
```
apis:
  - name: api_products
      attributes:
        request_path: /products
        upstream_url: http://products.app.internal
      plugins:
        - name: file-log
          attributes:
            config:
              path: "/usr/local/kong/logs/kong.log"
        - name: trace
        - name: key-auth
          attributes:
              config:
                hide_credentials: true
                key_names:
                  - apikey
consumers:
    - username: admin
      credentials:
        - name: key-auth
          attributes:
            key: ThisTokenIsNotSoSecretChangeIt
```

The config looks it was imported correctly:

Request: `curl localhost:8001/consumers`
Response: 
```
{
    "data":[
        {
            "username":"admin",
            "created_at":1466764389000,
            "id":"9a746cee-81af-426f-a54c-04d6ea522f23"
        }
    ],
    "total":1
}

```
Request: `
curl localhost:8001/consumers/admin/key-auth`
Response:
```
{
    "data":[
        {
            "created_at":1466764389000,
            "consumer_id":"9a746cee-81af-426f-a54c-04d6ea522f23",
            "key":"ThisTokenIsNotSoSecretChangeIt",
            "id":"42bc0e6d-d5eb-40dc-990a-be8828ddcb25"
        }
    ],
    "total":1
}
```
However when I try to actually use the key:

Request: `curl -H "apikey: ThisTokenIsNotSoSecretChangeIt" localhost:8000/products`

Response:

```
{
    "message":"No API Key found in headers, body or querystring"
}
```
If I use an invalid key I get:
Request: `curl -H "apikey: AnotherRandomKey" localhost:8000/products`

Response:

```
{
    "message":"Invalid authentication credentials"
}
```
However if I delete the API and plugin and re-add them via curl requests then everything works without any problems. I think it's something related to cache but no idea how to debug this. Any advice?
