### ISSUE TITLE
Kong freezes when starting with an invalid Cassandra host

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#168]
When starting Kong with an invalid Cassandra host I noticed it gets stuck.

![screen shot 2015-04-27 at 9 59 23 pm](https://cloud.githubusercontent.com/assets/24260/7363060/b3058368-ed28-11e4-85c2-5c05d9f001c8.png)

```yml
# Databases configuration
databases_available:
  cassandra:
    properties:
      hosts: "example.com"
      port: 9042
      timeout: 1000
      keyspace: kong
      keepalive: 60000
```
