### ISSUE TITLE
Default request host

### ISSUE THREAD

**Issue by robertlacok** [Mashape/kong#1858]
### Summary

We use kong to route traffic to different apis using different request hosts, i.e. api-1.domain.com. However, when we try to access api-which-isnt-added.domain.com (basically any other prefix) kong routes traffic to a one of the added apis, as if it selected one by default. We would prefer a 404 message. 

Is this expected behaviour? Is there a way to set this up?

### Additional Details & Logs

- Kong version 0.9.5  
- Deployed on Kubernetes in GKE

**Comment by Tieske** [comment]
it should give a message that there is no api. Have some details? configuration of apis and the exact request (host and path) that gets routed into the wrong api?

**Comment by thibaultcha** [comment]
@robertlacok Maybe you registered your API with a wildcard domain: `*.domain.com`?

**Comment by robertlacok** [comment]
I tinkered a little bit with it, removed the 'default' API from kong and added it back with the exact same settings and now it behaves correctly.  

The configuration was something like this (yaml from kongfig for readability):
```
    - name: demo-building
       plugins:
         - name: acl
           attributes:
             config:
               whitelist:
                 - admin
       attributes:
         request_host: building.api.domain.com
         request_path: ''
         strip_request_path: false
         preserve_host: false
         upstream_url: 'http://demo-building.default.svc.cluster.local:5001'
```
Very basic, no wildcards. Plus key-auth and http-log plugins for all APIs. Running inside kubernetes on GKE. 

Any request host that wasn't registered with kong got routed to that API, and any path was then evaluated by the server it was pointing to - i.e. non-existing path would give 404 but an existing one would give a 'correct' response. 

At this point I am not sure how to recreate it after it went away, but I haven't changed any of the settings. I will try to investigate some more to find out what happened.
