### ISSUE TITLE
Kong on kubernetes

### ISSUE THREAD

**Issue by geostant** [Mashape/kong#1892]
### Summary

Kong container fails with the following error message in the container logs:
```
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: No private IP address found, and explicit IP not provided
```

### Steps To Reproduce

1. Deploy Cassandra + service in kubernetes
2. Deploy Kong
3. Deploy kong Service

### Additional Details & Logs

- Kong version (`0.9.5`)
- Operating System (`kubernetes on ubuntu`)

#### Cassandra Deployment
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-database
    spec:
      containers:
      - name: kong-database
        image: cassandra:2.2
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: cassandra-data
      volumes:
      - name: cassandra-data
        hostPath:
          path: /mnt/data/cassandra-1
```

#### Cassandra Service
```
---
kind: Service
apiVersion: v1
metadata:
  name: kong-database
  labels:
    app: kong-database
spec:
  ports:
  - port: 9042
    targetPort: 9042
    name: cassandra
  selector:
    name: kong-database
  type: ClusterIP
```

#### Kong deployment
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
    spec:
      containers:
        - name : kong:
          image: kong
          env:
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: kong-database
```

#### Kong service
```
---
kind: Service
apiVersion: v1
metadata:
  name: kong
  labels:
    name: kong
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: kong-request
  - port: 8001
    targetPort: 8001
    name: kong-admin
  selector:
    name: kong
  type: NodePort
```
