### ISSUE TITLE
Kong cluster advertise choosing loopback address when cluster_listen is 0.0.0.0

### ISSUE THREAD

**Issue by jeremysmitherman** [Mashape/kong#2037]
### Summary

Kong cluster advertise choosing loopback address

### Steps To Reproduce

1. Set cluster_listen to 0.0.0.0:7946
2. Do not set cluster_advertise
3. See that in database cluster_listening_address on nodes table is 127.0.0.1 and kong cluster members doesn't list remote members

### Additional Details & Logs

- Kong version .10 rc3
- Centos7

**Comment by djMax** [comment]
I see this also on 0.9 on kubernetes.

**Comment by djMax** [comment]
For kubernetes, I solved this with the following in the deployment:

```
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: KONG_CLUSTER_ADVERTISE
          value: $(POD_IP):7946
```
