### ISSUE TITLE
feature: Kubernetes clustering IP and PORT issues

### ISSUE THREAD

**Issue by s4mur4i** [Mashape/kong#2098]
### Summary

To be able to use a kong cluster in kubernetes, the cluster_advertise value would need to be revised to two variables
cluster_advertise_address
cluster_advertise_port

When trying to inject with env variable concat, it will not be resolved:

The reason for having it under advertise2, is that the pod can start succesfully. in other case it will fail to start and no environment information would be available.

deployment environment variables:
```
          - name: KONG_CLUSTER_ADVERTISE2
            value: $(KONG_CLUSTER_IP):7946
          - name: KONG_CLUSTER_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
```

running pod environment variables:
```
KONG_CLUSTER_IP=172.20.193.96
KONG_CLUSTER_ADVERTISE=$(KONG_CLUSTER_IP):7946
```

Looking around kubernetes issues, this was requested and is currently not possible.
One workaround would be to to inject two variables, and in a startup script parse these, and export the variable, but that would be quite hacky.
