### ISSUE TITLE
 [cassandra error] All hosts tried for query failed. kong-database: Host considered DOWN.

### ISSUE THREAD

**Issue by akhildangore** [Mashape/kong#2139]
Hello Team,

I did the installation of kong using kubernetes, I followed below link for installation:
http://mattharris.org/2016/07/30/kong-with-kubernetes/

With reference with above link, I have created two files Kong-App.yml and Kong-Db.yml.
and run below command:

1. kubectl create -f Kong-Db.yml
2. kubectl create -f Kong-App.yml

Notes: I have kubernetes cluster of three nodes. 

### Additional Details & Logs

- Kong version (`$ kong version`):  0.9.9
- Kong debug-level startup logs (`$ kong start --vv`)
`2017/02/28 12:51:14 [verbose] Kong: 0.9.9
2017/02/28 12:51:14 [debug] ngx_lua: 10006
2017/02/28 12:51:14 [debug] nginx: 1011002
2017/02/28 12:51:14 [debug] Lua: LuaJIT 2.1.0-beta2
2017/02/28 12:51:14 [debug] PRNG seed: 481037523712
2017/02/28 12:51:14 [verbose] no config file found at /etc/kong.conf
2017/02/28 12:51:14 [verbose] no config file found at /etc/kong/kong.conf
2017/02/28 12:51:14 [verbose] no config file, skipping loading
2017/02/28 12:51:14 [debug] KONG_CASSANDRA_CONTACT_POINTS ENV found with "kong-database"
2017/02/28 12:51:14 [debug] KONG_DATABASE ENV found with "cassandra"
2017/02/28 12:51:14 [debug] admin_listen = "0.0.0.0:8001"
2017/02/28 12:51:14 [debug] anonymous_reports = true
2017/02/28 12:51:14 [debug] cassandra_consistency = "ONE"
2017/02/28 12:51:14 [debug] cassandra_contact_points = {"kong-database"}
2017/02/28 12:51:14 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/02/28 12:51:14 [debug] cassandra_keyspace = "kong"
2017/02/28 12:51:14 [debug] cassandra_port = 9042
2017/02/28 12:51:14 [debug] cassandra_repl_factor = 1
2017/02/28 12:51:14 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/02/28 12:51:14 [debug] cassandra_ssl = false
2017/02/28 12:51:14 [debug] cassandra_ssl_verify = false
2017/02/28 12:51:14 [debug] cassandra_timeout = 5000
2017/02/28 12:51:14 [debug] cassandra_username = "kong"
2017/02/28 12:51:14 [debug] cluster_listen = "0.0.0.0:7946"
2017/02/28 12:51:14 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/02/28 12:51:14 [debug] cluster_profile = "wan"
2017/02/28 12:51:14 [debug] cluster_ttl_on_failure = 3600
2017/02/28 12:51:14 [debug] custom_plugins = {}
2017/02/28 12:51:14 [debug] database = "cassandra"
2017/02/28 12:51:14 [debug] dnsmasq = true
2017/02/28 12:51:14 [debug] dnsmasq_port = 8053
2017/02/28 12:51:14 [debug] log_level = "notice"
2017/02/28 12:51:14 [debug] lua_code_cache = "on"
2017/02/28 12:51:14 [debug] lua_package_cpath = ""
2017/02/28 12:51:14 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/02/28 12:51:14 [debug] lua_ssl_verify_depth = 1
2017/02/28 12:51:14 [debug] mem_cache_size = "128m"
2017/02/28 12:51:14 [debug] nginx_daemon = "on"
2017/02/28 12:51:14 [debug] nginx_optimizations = true
2017/02/28 12:51:14 [debug] nginx_worker_processes = "auto"
2017/02/28 12:51:14 [debug] pg_database = "kong"
2017/02/28 12:51:14 [debug] pg_host = "127.0.0.1"
2017/02/28 12:51:14 [debug] pg_port = 5432
2017/02/28 12:51:14 [debug] pg_ssl = false
2017/02/28 12:51:14 [debug] pg_ssl_verify = false
2017/02/28 12:51:14 [debug] pg_user = "kong"
2017/02/28 12:51:14 [debug] prefix = "/usr/local/kong/"
2017/02/28 12:51:14 [debug] proxy_listen = "0.0.0.0:8000"
2017/02/28 12:51:14 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/02/28 12:51:14 [debug] serf_path = "serf"
2017/02/28 12:51:14 [debug] ssl = true
2017/02/28 12:51:14 [verbose] prefix in use: /usr/local/kong
2017/02/28 12:51:14 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/02/28 12:51:14 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/02/28 12:51:14 [debug] searching for OpenResty 'resty' executable
2017/02/28 12:51:14 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.1'
2017/02/28 12:51:14 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/02/28 12:51:14 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/02/28 12:51:14 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/02/28 12:51:14 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
`
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
`2017/02/28 12:54:43 [error] 70#0: *27 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:55:13 [error] 70#0: *28 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:55:43 [error] 70#0: *29 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:56:13 [error] 70#0: *30 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:56:43 [error] 70#0: *31 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:57:13 [error] 70#0: *32 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:57:43 [error] 70#0: *33 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:58:13 [error] 70#0: *34 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:58:43 [error] 70#0: *35 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
2017/02/28 12:59:13 [error] 70#0: *36 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] No query id found in cache for prepared query, context: ngx.timer
`
- Kong configuration (registered APIs/Plugins & configuration file)
`this is initial setup, no apis aor plugin yet`
- Operating System: `kubernetes host machine is ubuntu 16.04`

**Comment by shashiranjan84** [comment]
Please use template as its mentioned in this repo https://github.com/Mashape/kong-dist-kubernetes. Feel free to reopen ticket if you still facing the issue.

**Comment by akhildangore** [comment]
Hello @shashiranjan84,

I am using above template but i did some changes like:
cassandra image: cassandra:2.2 not gcr.io/google-samples/cassandra:v11
kong image: kong not mashape/kong:cassandra3

And  I am getting below errors:
````
2017/03/01 06:48:37 [warn] 6#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: Error during migration 2015-01-12-175310_init_schema: [Invalid] unconfigured table plugins

  Run with --v (verbose) or --vv (debug) for more details
migrating core for keyspace kong
core migrated up to: 2015-01-12-175310_skeleton

**Comment by shashiranjan84** [comment]
Official cassandra:2.2 is not cluster aware so `gcr.io/google-samples/cassandra:v11` should be used as it has custom seed provider. Also why you using `mashape/kong:cassandra3`?

if you want to try latest development Kong version try following template


```
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-ssl
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: kong-rc
        app: kong
    spec:
      containers:
      - name: kong
        image: mashape/kong:0.10.0rc4
        env:
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: $(CASSANDRA_SERVICE_HOST)
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "2"
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        command: [ "/bin/sh", "-c", "KONG_CLUSTER_ADVERTISE=$(KONG_HOST_IP):7946 KONG_NGINX_DAEMON='off' kong start && env" ]
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP

```

for migration issue, try provisioning one kong and one Cassandra instance 1st and then scale.
