### ISSUE TITLE
PUT /snis : created_at is required

### ISSUE THREAD

**Issue by VEBERArnaud** [Mashape/kong#2800]
### Summary

When I try to PUT a sni, i receive a `400 Bad Request` with body:

```json
{
    "created_at": "created_at is required"
}
```

### Steps To Reproduce

1. Create a certificate (`POST /certificates`)
```bash
❯ http POST 127.0.0.1/certificates Host:test.kong.localhost cert="-----BEGIN CERTIFICATE-----..." key="-----BEGIN RSA PRIVATE KEY-----..."
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Content-Length: 156
Content-Type: application/json; charset=utf-8
Date: Mon, 14 Aug 2017 02:13:20 GMT
Server: kong/0.10.3

{
    "cert": "-----BEGIN CERTIFICATE-----...",
    "created_at": 1502676800000,
    "id": "e05b9be7-7f2f-405b-97e6-3ddb699975cb",
    "key": "-----BEGIN RSA PRIVATE KEY-----..."
}
```

2. Update or create sni (`PUT /snis`)
```bash
❯ http PUT 127.0.0.1/snis Host:test.kong.localhost name="example.com" ssl_certificate_id="e05b9be7-7f2f-405b-97e6-3ddb699975cb"
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Length: 40
Content-Type: application/json; charset=utf-8
Date: Mon, 14 Aug 2017 02:14:35 GMT
Server: kong/0.10.3

{
    "created_at": "created_at is required"
}
```

### Additional Details & Logs

I'm using the official docker image `kong:0.10.3`

```yml
version: "3"
services:
    db:
        image: postgres:9.4
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
        expose:
            - 5432

    kong:
        image: kong:0.10
        depends_on:
            - db
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=db
        labels:
            - "traefik.frontend.rule=Host:test.kong.localhost"
            - "traefik.port=8001"
        links:
            - db
        restart: unless-stopped

    proxy:
        image: traefik
        command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
```
