### ISSUE TITLE
Migrations fails - can't resolve cassandra host throught docker service discovery

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [Mashape/kong#2949]
### Summary

Migrations doesn't work if docker cassandra container name is used for service discovery. If IP is provided instead it works.

#### This works:

172.19.0.2 - IP of cassandra container

```
docker run --rm --network dev_env_net -e KONG_DATABASE=cassandra -e KONG_PG_HOST=172.19.0.2 -e KONG_CASSANDRA_CONTACT_POINTS=172.19.0.2 kong kong migrations up
```

#### This doesn't work:

```
docker run --rm --network dev_env_net -e KONG_DATABASE=cassandra -e KONG_PG_HOST=cassandra-container-name -e KONG_CASSANDRA_CONTACT_POINTS=cassandra-container-name kong kong migrations up
```

```
2017/Error: 
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: [cassandra error] could not find coordinator: all hosts tried for query failed. cassandra-container-name: host seems unhealthy, considering it down ([toip() name lookup failed]: recursion detected)
stack traceback:
    [C]: in function 'assert'
    /usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: in function 'cmd_exec'
    /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
    [C]: in function 'xpcall'
    /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
    /usr/local/bin/kong:7: in function 'file_gen'
    init_worker_by_lua:39: in function <init_worker_by_lua:37>
    [C]: in function 'xpcall'
    init_worker_by_lua:46: in function <init_worker_by_lua:44>
```

#### Even do ping through service discovery kong > cassandra works like a charm:
```
$ docker run --rm --network dev_env_net kong ping cassandra-container-name
PING cassandra-container-name (172.19.0.2) 56(84) bytes of data.
64 bytes from cassandra-container-name.dev_env_net (172.19.0.2): icmp_seq=1 ttl=64 time=0.158 ms
64 bytes from cassandra-container-name.dev_env_net (172.19.0.2): icmp_seq=2 ttl=64 time=0.121 ms
64 bytes from cassandra-container-name.dev_env_net (172.19.0.2): icmp_seq=3 ttl=64 time=0.118 ms
```

### Steps To Reproduce

1. Create cassandra docker container
```
docker volume create --name "cassandra-volume"
docker run -d \
--name cassandra-container-name \
--network dev_env_net \
--volume "cassandra-volume":/var/lib/cassandra \
-p 9042:9042 \
cassandra
```
2. Run kong migrations
```
docker run --rm \
--network dev_env_net \
-e "KONG_DATABASE=cassandra" \
-e "KONG_PG_HOST=cassandra-container-name" \
-e "KONG_CASSANDRA_CONTACT_POINTS=cassandra-container-name" \
kong kong migrations up
```

### Additional Details & Logs

- Kong version `kong version 0.11.0`
- Operating System - official kong docker image - container fired with tag: `kong:latest`

**Comment by vukasin-nikodijevic** [comment]
Another important thingy is that `cassandra` must be fully bootstrapped(ready to accept connections) at the time of running kong migrations. On my host it takes around 35sec. 

This issue pretty much blocks me to use `docker-compose` to bootstrap development environment but shell script.

This is how kong run.sh looks like with all workarounds:

```
#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${DIR}/../shared.sh"

CONTAINER_NAME="ec-platform-kong"
CASSANDRA_IP=$(docker inspect ec-platform-cassandra --format "{{( index .NetworkSettings.Networks \"${LOCAL_DEV_NETWORK_NAME}\").IPAddress}}")

echo "Sleeping 40s";
sleep 40s;

ping -c 4 ${CASSANDRA_IP}
nc -z ${CASSANDRA_IP} 9042

if [[ $? -eq 1 ]]
then
    echo "nc -z ${CASSANDRA_IP} 9042 - FAILED"
fi

# Run migrations
docker run --rm \
--network "${LOCAL_DEV_NETWORK_NAME}" \
-e "KONG_DATABASE=cassandra" \
-e "KONG_CASSANDRA_CONTACT_POINTS=${CASSANDRA_IP}" \
kong kong migrations up

# Run kong container
docker run -d \
--name "${CONTAINER_NAME}" \
--network "${LOCAL_DEV_NETWORK_NAME}" \
-e "KONG_DATABASE=cassandra" \
-e "KONG_CASSANDRA_CONTACT_POINTS=${CASSANDRA_IP}" \
-p 8000:8000 \
-p 8443:8443 \
-p 8001:8001 \
-p 8444:8444 \
kong

docker network connect bridge "${CONTAINER_NAME}"

```

**Comment by hutchic** [comment]
I don't have any problem with cassandra over the docker overlay network

```
version: '2.1'
services:
  kong-database:
    image: healthcheck/cassandra
  kong-migration:
    image: kong:latest
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations up
  kong:
    image: kong:latest
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
```

Also we'd prefer to keep service healthcheck launch order etc outside of the official docker images. You can see how I did it above but that's limited to docker-compose 2.1 but docker swarm and kubernetes etc all have similar mechanisms available
