### ISSUE TITLE
Kong (openresty) cannot resolve linked containers on tutum platform

### ISSUE THREAD

**Issue by adamclerk** [Mashape/kong#428]
I'm using kong within the tutum platform and I'm having a problem with linking containers. 

I have kong running and configured. 
If I expose port 80 on my api and use a FQDN, kong can access my api...

```
target_url=http://lb.*.tutum.io
```

However, when I try to make the api only accessible to the containers on the platform via a service link...

https://support.tutum.co/support/solutions/articles/5000012181-service-discovery-and-links

thereby adding a new dns entry for the service and configuring kong with the following...

```
target_url=http://lb
```

Openresty cannot resolve the service name. However, I can ping the service name from within the container and do an nslookup from within the container...

## PING
```
# ping lb                                                                       
PING lb.ee9f2e8f-fc3d-4621-9e8a-9aa3d1136a54.local.tutum.io (10.7.0.7): 48 data 
bytes                                                                           
56 bytes from 10.7.0.7: icmp_seq=0 ttl=64 time=0.085 ms                         
56 bytes from 10.7.0.7: icmp_seq=1 ttl=64 time=0.053 ms                         
^C--- lb.ee9f2e8f-fc3d-4621-9e8a-9aa3d1136a54.local.tutum.io ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss                       
round-trip min/avg/max/stddev = 0.053/0.069/0.085/0.000 ms
```

## NSLOOKUP DNSMASQ(LOCAL)
```
# nslookup -port=8053 lb localhost                                              
Server:         localhost                                                       
Address:        ::1#8053                                                        
                                                                                
Non-authoritative answer:                                                       
Name:   lb.ee9f2e8f-fc3d-4621-9e8a-9aa3d1136a54.local.tutum.io                  
Address: 10.7.0.7
```

## NSLOOKUP
```
# nslookup lb                                                                   
Server:         172.77.0.2                                                      
Address:        172.77.0.2#53                                                   
                                                                                
Non-authoritative answer:                                                       
Name:   lb.ee9f2e8f-fc3d-4621-9e8a-9aa3d1136a54.local.tutum.io                  
Address: 10.7.0.7
```

## OPENRESTY/NGINX ERROR LOG
```
2015/07/25 15:57:13 [error] 114#0: *1 lb could not be resolved (3: Host not foun
d), client: XXX.XX.XXX.211, server: _, request: "GET /secapi/v0/4/001 HTTP/1.1",
 host: "lb"
```

Any help would be appreciated.

**Comment by adamclerk** [comment]
Here is what I have currently in my `nginx.conf` under the resolver directive.

```
resolver 127.0.0.1:8053;
```

I've tried hard coding the nameserver with
```
resolver 172.77.0.2;
``` 

But still no luck openresty/nginx cannot resolve 'http://lb/'

**Comment by adamclerk** [comment]
If you would like to try this setup on tutum please use the following stackfile
```
cass:
  image: 'cassandra:latest'
  ports:
    - '9042:9042'
kong:
  image: 'adamclerk/my-kong:latest'
  links:
    - 'cass:cassandra'
    - lb
  ports:
    - '8000:8000'
    - '8001:8001'
lb:
  image: 'tutum/haproxy:0.1'
  expose:
    - '80'
    - '443'
    - '1936'
  links:
    - web
  restart: always
  roles:
    - global
web:
  image: 'tutum/hello-world'
  ports:
    - '80'
  restart: always
  target_num_containers: 2
```
