### ISSUE TITLE
Kong with docker-compose v2. problem with network

### ISSUE THREAD

**Issue by yuriyzinchenko** [Mashape/kong#936]
Kong can't resolve cassandra host when starting. But the host ping is well from kong container. Maybe I should do it differently?

My docker-compose.yml:

```
version: 2

services:
  kong:
    image: mashape/kong:0.6.0
    ports:
      - 8000:8000
      - 8001:8001
      - 7946:7946
    networks:
      - cassandra

  cassandra:
    image: cassandra:2.2.4
    networks:
      - cassandra

networks:
  cassandra:
    driver: bridge
```

Logs from kong:
```
connect: Network is unreachable
[INFO] Kong 0.6.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] database...........cassandra ssl=verify=false enabled=false keyspace=kong replication_factor=1 replication_strategy=SimpleStrategy contact_points=cassandra:9042 data_centers=
[INFO] Leaving cluster..
[ERR] Cassandra error: NoHostAvailableError: All hosts tried for query failed. cassandra:9042: SocketError: Network is unreachable for socket with peer cassandra:9042.
[ERR] Could not start Kong
```
Ping cassandra from kong container:

```
PING cassandra (172.22.0.2) 56(84) bytes of data.
64 bytes from automicroassembly_cassandra_1.automicroassembly_cassandra (172.22.0.2): icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from automicroassembly_cassandra_1.automicroassembly_cassandra (172.22.0.2): icmp_seq=3 ttl=64 time=0.116 ms
64 bytes from automicroassembly_cassandra_1.automicroassembly_cassandra (172.22.0.2): icmp_seq=4 ttl=64 time=0.052 ms
64 bytes from automicroassembly_cassandra_1.automicroassembly_cassandra (172.22.0.2): icmp_seq=5 ttl=64 time=0.065 ms

--- cassandra ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 3998ms
rtt min/avg/max/mdev = 0.052/0.076/0.116/0.024 ms
```
Docker version:

```
Client:
 Version:      1.10.0-rc2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c1cdc6e
 Built:        Wed Jan 27 22:31:21 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c1cdc6e
 Built:        Wed Jan 27 22:31:21 2016
 OS/Arch:      linux/amd64
```
Compose version:

```
docker-compose version 1.6.0rc2, build 695c692
docker-py version: 1.7.0-rc3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```
